### ISSUE TITLE
hello, c++ new thread bsod

### ISSUE THREAD

**Issue by rootaydn** [EBalloon/Rw-No-Attach#1]
Hello, I don't get bsod when I use KeAttachProcess/KeStackAttachProcess.

Rw-No-Attach thread bsod.  windows 11 latesh.

sorry for bad english

no problem with single core

std::thread overlay_thread(renderEsp);

void renderEsp() {
	std::this_thread::sleep_for(std::chrono::milliseconds(40));
	std::unique_ptr<std::vector<BaseResource>> t_oreList = std::make_unique<std::vector<BaseResource>>();

	DWORD64 EntityRealm = Read<DWORD64>(base_networkable + 0xB8);
	DWORD64 ClientEntities = Read<DWORD64>(EntityRealm);
	DWORD64 ClientEntities_list = Read<DWORD64>(ClientEntities + 0x10);
	DWORD64 ClientEntities_values = Read<DWORD64>(ClientEntities_list + 0x28);

	if (!ClientEntities_values) return;
	int EntityCount = Read<int>(ClientEntities_values + 0x10);

	DWORD64 EntityBuffer = Read<DWORD64>(ClientEntities_values + 0x18);

	for (int i = 0; i < EntityCount; i++)
	{

		DWORD64 Entity = Read<DWORD64>(EntityBuffer + 0x20 + (i * 0x8));//BaseEntity
		//std::cout<<"Entity:" << Entity << std::endl;
		if (Entity <= 100000) continue;

		DWORD64 Object = Read<DWORD64>(Entity + 0x10);
		if (Object <= 100000) continue;

		DWORD64 ObjectClass = Read<DWORD64>(Object + 0x30); //CGameObject
		if (ObjectClass <= 100000) continue;

		if (Read<int16_t>(ObjectClass + 0x54) == 6)
		{
			//std::cout << "Object:" << Object << std::endl;
		}

		//int16_t Tag = Read<int16_t>(Object + 0x54);

		//if (Tag == 5)
		//{
		//	LocalViewMatrixGuncelle();
		//}

		auto BNname = ReadNative(ObjectClass + 0x60);

		//if (BNname.find("LocalPlayer") != std::string::npos) {

			//DWORD64 gameObject = Read<DWORD64>(ObjectClass + 0x30);
			//DWORD64 Trans = Read<DWORD64>(gameObject + 0x8);
			//DWORD64 Vec = Read<DWORD64>(Trans + 0x38);
			//Vector3 pos = Read<Vector3>(Vec + 0x90);

			//DWORD64 myLocalPlayer = Read<DWORD64>(Object + 0x28);
			//DWORD64 Movement = Read<DWORD64>(myLocalPlayer + oBaseMovement);

			//std::cout << "Movement  : " << Movement << std::endl;
			//Vector3 vel = Read<Vector3>(Movement + 0xD4);
			//std::cout << "Local Kordinat  : " << vel.x << " " << vel.y << " " << vel.z << std::endl;

		//}

		if (BNname.find("autospawn/resource/ores") != std::string::npos || BNname.find("autospawn/collectable/") != std::string::npos) {

			if (BNname.find("stone-ore.prefab") != std::string::npos) {

				DWORD64 gameObject = Read<DWORD64>(ObjectClass + 0x30);
				DWORD64 Trans = Read<DWORD64>(gameObject + 0x8);
				DWORD64 Vec = Read<DWORD64>(Trans + 0x38);
				Vector3 pos = Read<Vector3>(Vec + 0x90);
				LocalViewMatrixGuncelle();
				//std::cout << "Local Kordinat  : " << position.x << " " << position.y << " " << position.z << std::endl;
				//Vector2 screen{};
				//if (world_to_screen(pos, screen))
				//{
					//ImGui::GetOverlayDrawList()->AddText(ImVec2(screen.x, screen.y), ImColor(255, 0, 27), "Tas");
				//}

				auto entity = Read<uintptr_t>(gameObject + 0x18);

				std::unique_ptr<BaseResource> oreEntity = std::make_unique<BaseResource>(entity, Trans, ObjectClass);

				t_oreList->push_back(*oreEntity); continue;

				//Vector2 screen{};
				//if (world_to_screen(pos, screen))
				//{
					//ImGui::GetOverlayDrawList()->AddText(ImVec2(screen.x, screen.y), ImColor(255, 0, 27), "Tas");
				//}
			}

		}

	}

	oreList->clear();
	*oreList = *t_oreList;

}

**Comment by rootaydn** [comment]
no problem with single core

**Comment by EBalloon** [comment]
> Hello, I don't get bsod when I use KeAttachProcess/KeStackAttachProcess.
> 
> Rw-No-Attach thread bsod. windows 11 latesh.
> 
> sorry for bad english
> 
> no problem with single core
> 
> std::thread overlay_thread(renderEsp);
> 
> void renderEsp() { std::this_thread::sleep_for(std::chrono::milliseconds(40)); std::unique_ptr<std::vector> t_oreList = std::make_unique<std::vector>();
> 
> ```
> DWORD64 EntityRealm = Read<DWORD64>(base_networkable + 0xB8);
> DWORD64 ClientEntities = Read<DWORD64>(EntityRealm);
> DWORD64 ClientEntities_list = Read<DWORD64>(ClientEntities + 0x10);
> DWORD64 ClientEntities_values = Read<DWORD64>(ClientEntities_list + 0x28);
> 
> if (!ClientEntities_values) return;
> int EntityCount = Read<int>(ClientEntities_values + 0x10);
> 
> DWORD64 EntityBuffer = Read<DWORD64>(ClientEntities_values + 0x18);
> 
> for (int i = 0; i < EntityCount; i++)
> {
> 
> 	DWORD64 Entity = Read<DWORD64>(EntityBuffer + 0x20 + (i * 0x8));//BaseEntity
> 	//std::cout<<"Entity:" << Entity << std::endl;
> 	if (Entity <= 100000) continue;
> 
> 	DWORD64 Object = Read<DWORD64>(Entity + 0x10);
> 	if (Object <= 100000) continue;
> 
> 	DWORD64 ObjectClass = Read<DWORD64>(Object + 0x30); //CGameObject
> 	if (ObjectClass <= 100000) continue;
> 
> 	if (Read<int16_t>(ObjectClass + 0x54) == 6)
> 	{
> 		//std::cout << "Object:" << Object << std::endl;
> 	}
> 
> 	//int16_t Tag = Read<int16_t>(Object + 0x54);
> 
> 	//if (Tag == 5)
> 	//{
> 	//	LocalViewMatrixGuncelle();
> 	//}
> 
> 
> 	auto BNname = ReadNative(ObjectClass + 0x60);
> 
> 
> 	//if (BNname.find("LocalPlayer") != std::string::npos) {
> 
> 		//DWORD64 gameObject = Read<DWORD64>(ObjectClass + 0x30);
> 		//DWORD64 Trans = Read<DWORD64>(gameObject + 0x8);
> 		//DWORD64 Vec = Read<DWORD64>(Trans + 0x38);
> 		//Vector3 pos = Read<Vector3>(Vec + 0x90);
> 
> 		//DWORD64 myLocalPlayer = Read<DWORD64>(Object + 0x28);
> 		//DWORD64 Movement = Read<DWORD64>(myLocalPlayer + oBaseMovement);
> 
> 		//std::cout << "Movement  : " << Movement << std::endl;
> 		//Vector3 vel = Read<Vector3>(Movement + 0xD4);
> 		//std::cout << "Local Kordinat  : " << vel.x << " " << vel.y << " " << vel.z << std::endl;
> 
> 	//}
> 
> 	if (BNname.find("autospawn/resource/ores") != std::string::npos || BNname.find("autospawn/collectable/") != std::string::npos) {
> 
> 		if (BNname.find("stone-ore.prefab") != std::string::npos) {
> 
> 			DWORD64 gameObject = Read<DWORD64>(ObjectClass + 0x30);
> 			DWORD64 Trans = Read<DWORD64>(gameObject + 0x8);
> 			DWORD64 Vec = Read<DWORD64>(Trans + 0x38);
> 			Vector3 pos = Read<Vector3>(Vec + 0x90);
> 			LocalViewMatrixGuncelle();
> 			//std::cout << "Local Kordinat  : " << position.x << " " << position.y << " " << position.z << std::endl;
> 			//Vector2 screen{};
> 			//if (world_to_screen(pos, screen))
> 			//{
> 				//ImGui::GetOverlayDrawList()->AddText(ImVec2(screen.x, screen.y), ImColor(255, 0, 27), "Tas");
> 			//}
> 
> 			auto entity = Read<uintptr_t>(gameObject + 0x18);
> 
> 			std::unique_ptr<BaseResource> oreEntity = std::make_unique<BaseResource>(entity, Trans, ObjectClass);
> 
> 			t_oreList->push_back(*oreEntity); continue;
> 
> 			//Vector2 screen{};
> 			//if (world_to_screen(pos, screen))
> 			//{
> 				//ImGui::GetOverlayDrawList()->AddText(ImVec2(screen.x, screen.y), ImColor(255, 0, 27), "Tas");
> 			//}
> 		}
> 
> 	}
> 
> }
> 
> oreList->clear();
> *oreList = *t_oreList;
> ```
> 
> }

show the code in the driver
did you test on win 10? this code was made from it

**Comment by EBalloon** [comment]
> Hello, I don't get bsod when I use KeAttachProcess/KeStackAttachProcess.
> 
> Rw-No-Attach thread bsod. windows 11 latesh.
> 
> sorry for bad english
> 
> no problem with single core
> 
**show the code in the driver**
**did you test on win 10? this code was made from it**
